### ISSUE TITLE
[2020-09-30] weekly scrum

### ISSUE THREAD

**Issue by Brew-Brew** [covid19-cau/capstone-design-project#22]
- Schedule check
- Speaking of each issue
- Check the work this week
- Check the progress of the backend and check the sharing
- Next announcement story
- List of things to do to complete development on the 13th
    - Hyowon
        - DB basic design, table creation, etc.
        - jpa setting
    - Geunwoo
        - Controller class
            - Recommend content registration, modification, inquiry, deletion
            - User information inquiry
        - The part of the DAO
        - JPA support
    - Seungkyu
        - Admin UI development
        - API linkage

**Comment by Brew-Brew** [comment]
**What I did** (https://github.com/covid19-cau/capstone-design-project/projects/1)
- [Weekly scrum](https://github.com/covid19-cau/capstone-design-project/issues/22)
- [API spec update]
(https://docs.google.com/document/d/1vy7BKOI09kE4jbRatHS8Hb4naufkphGqUEl6zdg36Z8/edit#)
  - update api of listing and registering recomend contents 
- [add admin ui and seperate components with mock setting](https://github.com/covid19-cau/capstone-design-project/pull/10)
  - seperate components with ant-design built in component (recommend contents, user manage)
  - add mock data
<img width="1025" alt="스크린샷 2020-10-02 오후 3 32 07" src="https://user-images.githubusercontent.com/26598542/94894580-9da6fd80-04c4-11eb-9c9a-b9f6c16a3f2f.png">
<img width="1020" alt="스크린샷 2020-10-02 오후 3 31 59" src="https://user-images.githubusercontent.com/26598542/94894586-a1d31b00-04c4-11eb-9cb9-e2688fcd260c.png">

**Work Status**
- Develop client features (40%)
  - develop UI of admin page

**What I will do next week**
- [complete develop admin recomend contents manage page UI](https://github.com/covid19-cau/capstone-design-project/issues/18)
- [complete develop admin user manage page](https://github.com/covid19-cau/capstone-design-project/issues/19)

**Comment by HyowonSin** [comment]
What i did
* [Database design]

![Tables Diagram](https://user-images.githubusercontent.com/48724199/94985500-5129f380-0592-11eb-8a3f-3496a08ec445.png)

* [Insert Samples]

![Sample images](https://user-images.githubusercontent.com/48724199/94985501-5424e400-0592-11eb-97a1-53801287ad49.png)

* [JPA Learning]
* [JPA Setting]
** add dependecy
** set MySQL datasource
** Entity Class [...]
** Repository Interface [...]

 What to do
* Finish setting ( Create Service class, Create Controller, Set Properties ) 
* JPA CRUD mapping
* add API 


Problem & Solving
* The server could not be set up. 
->I downloaded EE version of Eclipse again.
* I needed to coordinate the classes created by the server developer with the databases I created. 
-> Meet and Collaborate Next Week
* I put the constraints using CHECK in the database column, but it was too cumbersome. 
-> It was changed in a way that gave meaning to numbers. It became easier and more comfortable.

Due to the Chuseok holiday, We couldn't meet This Week.
After the holiday, We plan to have a meeting to coordinate.
